kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: ceph-claim-dynamic-jenkins
spec:
 accessModes:
    - ReadWriteOnce
 resources:
   requests:
     storage: 10Gi
 storageClassName: ceph-storage

