FROM alpine:latest

MAINTAINER Mao "Chengfei chengfei.mao@baozun.com"

RUN apk update \
        && apk upgrade \
        && apk add --no-cache bash \
        bash-doc \
        bash-completion \
        && rm -rf /var/cache/apk/* \
        && /bin/bash

COPY ./glibc-2.28-r0.apk /usr/local
COPY ./sgerrand.rsa.pub /etc/apk/keys/

RUN apk add /usr/local/glibc-2.28-r0.apk

#RUN yum install -y net-tools
RUN mkdir -p /usr/local/jdk1.7.0_80
COPY ./jdk1.7.0_80 /usr/local/jdk1.7.0_80
RUN mkdir -p /usr/local/apache-tomcat-7.0.90
COPY ./apache-tomcat-7.0.90 /usr/local/apache-tomcat-7.0.90

ENV JAVA_HOME /usr/local/jdk1.7.0_80
ENV CATALINA_HOME /usr/local/apache-tomcat-7.0.90
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin

EXPOSE 8080

#启动时运行tomcat
CMD ["/usr/local/apache-tomcat-7.0.90/bin/catalina.sh","run"]
